# Project information
site_name: Faculdade de Arquitetura e Urbanismo
site_author: Grupo 03
site_url: https://Requisitos-de-Software.github.io/2022.1-Faculdade-de-Arquitetura-e-Urbanismo

# Repository
repo_name: 2022.1-Faculdade-de-Arquitetura-e-Urbanismo
repo_url: https://github.com/Requisitos-de-Software/2022.1-Faculdade-de-Arquitetura-e-Urbanismo

theme:
  name: "material"
  language: "pt"
  logo: "assets/logo_faunb.png"
  palette:
    primary: "grey"
    accent: "light grey"
  font:
    text: "Montserrat"
    code: "sans-serif"

plugins:
  - mkdocs-video

# Content Menu
nav:
  - Início: index.md
  - Planejamento: 
    - Cronograma: planejamento/cronograma-de-atividades.md
    - Sites Avaliados: planejamento/escolha-do-site.md
    - Metodologias: planejamento/metodologia-e-processos.md
    - Processo de Design: planejamento/processo-de-design.md
