name: Deploy - faunb
on:
  workflow_dispatch:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Deploy to github
        run: |
          mkdocs gh-deploy --force
